### ISSUE TITLE
Pretty task table print

### ISSUE THREAD

**Issue by unkcpz** [unkcpz/tatzelwurm#7]
- [x] count number of each type (#9)
- [x] filter task type (#8)
- [x] by default shows only running tasks. [#8]
